# YOUR NAME OR TITLE OF YOUR SITE
name: Juan Pablo Deplà

# YOUR BRAND/PERSONAL TAGLINE
tagline: Esculturas con desechos metálicos reciclados.

# YOUR/BRAND IMAGE URL
Image_URL: https://www.gravatar.com/avatar/0d73468bd0b0258eb61d9358352ecb7b?s=500

# CHANGE THE BACKGROUND IMAGE OF THE WEBSITE BY JUST ADDING THE IMAGE URL
Cover_Image: https://source.unsplash.com/random

# SOCIAL MEDIA
links:

  # IF YOU DON'T WANT TO USE ANY OF THE FOLLOWING, JUST LEAVE THE URL BLANK
  
    # INSTAGRAM
  - Name: Instagram
    URL: https://www.instagram.com
    Username: harsh98trivedi
    Color: '#DD2A7B'
    Icon-Class: fab fa-instagram


# STOP EDITING HERE ---------- YOU'VE REACHED THE END OF THE CONFIGURATION

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
# baseurl: /links

# Default Markdown Engine
markdown: kramdown
